"""Initial migration

Revision ID: 399fa9066149
Revises: 
Create Date: 2026-02-16 13:33:43.466595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399fa9066149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
